In [1]:
# Importing the libraries
import numpy as np

import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Importing the dataset
dataset = pd.read_csv('data.csv')
dataset.head(10)

high_GPA  math_SAT  verb_SAT  comp_GPA  univ_GPA
0      3.45       643       589      3.76      3.52
1      2.78       558       512      2.87      2.91
2      2.52       583       503      2.54      2.40
3      3.67       685       602      3.83      3.47
4      3.24       592       538      3.29      3.47
5      2.10       562       486      2.64      2.37
6      2.82       573       548      2.86      2.40
7      2.36       559       536      2.03      2.24
8      2.42       552       583      2.81      3.02
9      3.51       617       591      3.41      3.32

In [3]:
# independent variables (Gender,length) >>>>> features
X = dataset.iloc[:, [0,4]].values
# dependent variable (weight) >>>> output 
y = dataset.iloc[:, 4].values

y

array([3.52, 2.91, 2.4 , 3.47, 3.47, 2.37, 2.4 , 2.24, 3.02, 3.32, 3.59,
       2.54, 3.19, 3.71, 3.58, 3.4 , 3.73, 3.49, 2.25, 2.37, 3.29, 3.19,
       3.28, 3.37, 3.61, 3.81, 2.4 , 2.21, 3.58, 3.51, 3.62, 3.6 , 3.65,
       3.76, 2.27, 2.35, 3.17, 3.47, 3.  , 2.74, 3.37, 3.54, 3.28, 3.39,
       3.28, 3.19, 2.52, 3.08, 3.01, 3.42, 3.6 , 2.4 , 2.83, 2.38, 3.21,
       2.24, 3.4 , 3.07, 3.52, 3.47, 3.08, 3.38, 3.41, 3.64, 3.71, 3.01,
       3.37, 2.34, 3.29, 3.4 , 3.38, 3.28, 3.31, 3.42, 3.39, 3.51, 3.17,
       3.2 , 3.41, 3.29, 3.17, 3.12, 3.71, 3.5 , 3.34, 3.48, 3.44, 3.59,
       3.28, 3.  , 3.42, 3.41, 3.49, 3.28, 3.17, 3.24, 2.34, 3.28, 2.29,
       2.08, 3.64, 3.42, 3.25, 2.76, 3.41])

In [4]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)
y_test

array([2.4 , 3.38, 2.4 , 3.41, 3.48, 3.01, 3.73, 3.64, 3.4 , 3.19, 3.37,
       3.28, 2.4 , 3.71, 2.24, 3.62, 3.28, 3.61, 3.76, 3.02, 3.39])

In [5]:
from sklearn.svm import SVR
regressor = SVR()  # object or instance from SVR
regressor.fit(X_train, np.ravel(y_train,order='C')) # train the model


C:\Users\mahmoudRamadan\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
    gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
    tol=0.001, verbose=False)

In [6]:
# Predicting the Test set results
y_pred = regressor.predict(X_test)
y_pred

array([2.36227181, 3.38038483, 2.36212311, 3.41504408, 3.46675217,
       3.03238786, 3.68123414, 3.63790799, 3.37683494, 3.11992703,
       3.43159216, 3.28339657, 2.3896968 , 3.6397209 , 2.28204932,
       3.60638837, 3.20150723, 3.60734333, 3.68800783, 2.95183082,
       3.31909937])

In [7]:
# comparing actual data with predicted data
df= pd.DataFrame({'Actual': list(y_test), 'Predicted': y_pred})
df

Actual  Predicted
0     2.40   2.362272
1     3.38   3.380385
2     2.40   2.362123
3     3.41   3.415044
4     3.48   3.466752
5     3.01   3.032388
6     3.73   3.681234
7     3.64   3.637908
8     3.40   3.376835
9     3.19   3.119927
10    3.37   3.431592
11    3.28   3.283397
12    2.40   2.389697
13    3.71   3.639721
14    2.24   2.282049
15    3.62   3.606388
16    3.28   3.201507
17    3.61   3.607343
18    3.76   3.688008
19    3.02   2.951831
20    3.39   3.319099

In [8]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
from math import sqrt
print('Mean Absolute Error    :', mean_absolute_error(y_test, y_pred))
print('Mean Squared Error     :', mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', sqrt(mean_squared_error(y_test, y_pred)))

Mean Absolute Error    : 0.035914714169756036
Mean Squared Error     : 0.0020580264674757
Root Mean Squared Error: 0.04536547660364322


In [9]:
# # Visualising the Training set results
# plt.scatter(X_train, y_train, color = 'red')
# # plt.scatter(X_test, y_test, color = 'green')
# plt.plot(X_train, regressor.predict(X_train), color = 'blue')
# plt.title('SAT degrees')
# plt.xlabel('high_GPA')
# plt.ylabel('univ_GPA')
# plt.show()